# Generated by Django 4.1.5 on 2023-01-28 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('avaliacao_dia', models.CharField(blank=True, choices=[('p', 'Péssimo'), ('r', 'Ruim'), ('b', 'Bom'), ('o', 'Ótimo')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acontecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acontecimento', models.CharField(blank=True, choices=[('p', 'Positivo'), ('n', 'Negativo')], max_length=10, null=True)),
                ('descricao_acontecimento', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacao.avaliacao')),
            ],
        ),
    ]
